stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

build-and-push:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind

before_script:
  - apt-get update -y && apt-get install -y git openssh-client
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

script:
    - git clone git@gitlab.com:matias.nahuel.rosello-group/matias.nahuel.rosello-project.git

    # Build y push de Angular
    - docker build -t $CI_REGISTRY_IMAGE/angular-frontend:latest ./angular
    - docker push $CI_REGISTRY_IMAGE/angular-frontend:latest

    # Build y push de Flask
    - docker build -t $CI_REGISTRY_IMAGE/flask-backend:latest ./flask
    - docker push $CI_REGISTRY_IMAGE/flask-backend:latest
