stages:
  - deploy

variables:
  DOCKER_DRIVER: overlay2

# Antes de cualquier job, inicializamos SSH y hacemos login en Docker
.default_before_script: &default_before_script
  - 'which ssh-agent || ( apt-get update -y && apt-get install -y openssh-client git )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

# Job para desplegar Angular y Flask usando imágenes existentes
deploy-app:
  stage: deploy
  image: docker:24.0.5-git
  services:
    - docker:24.0.5-dind
  before_script:
    - *default_before_script
  script:
    # Traer las imágenes de Docker Hub
    - docker pull mrosello/leafnoise_angular:1.0.0
    - docker pull mrosello/leafnoise_flask:1.0.0

    # Opcional: etiquetar para GitLab Container Registry
    - docker tag mrosello/leafnoise_angular:1.0.0 $CI_REGISTRY_IMAGE/leafnoise_angular:1.0.0
    - docker tag mrosello/leafnoise_flask:1.0.0 $CI_REGISTRY_IMAGE/leafnoise_flask:1.0.0

    # Push a GitLab Container Registry
    - docker push $CI_REGISTRY_IMAGE/leafnoise_angular:1.0.0
    - docker push $CI_REGISTRY_IMAGE/leafnoise_flask:1.0.0

    # Levantar con Docker Compose
    - docker-compose up -d
